# Minimal configuration.yml example
homeassistant: true
permit_join: true
mqtt:
   base_topic: zigbee2mqtt
   server: mqtt://localhost
serial:
     port: /dev/ttyUSB0
frontend:
     port: 9090
advanced:
     pan_id: GENERATE
     ext_pan_id: [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08]
     network_key: GENERATE
